import { Database } from 'bun:sqlite';
import * as fs from 'fs';
import * as path from 'path';

import { BOOKS, TranslationCode, TRANSLATIONS } from '../lib/bible/canon';

const ASSETS_DIR = path.join(import.meta.dir, '../assets/bible');
const GENERATED_FILE = path.join(import.meta.dir, '../lib/bible/chapter-stats.generated.ts');

const stats: Record<string, [number, number][][]> = {};

for (const code of Object.keys(TRANSLATIONS) as TranslationCode[]) {
  const dbPath = path.join(ASSETS_DIR, `${code}.db`);
  if (!fs.existsSync(dbPath)) {
    throw new Error(`Missing ${dbPath}`);
  }

  // Open read-write to create index
  const db = new Database(dbPath, { readwrite: true });
  console.log(`Processing ${code}...`);

  // Assert exactly 66 books, contiguous 1-66
  const books = db.query(`SELECT id FROM ${code}_books ORDER BY id`).all() as {id: number}[];
  if (books.length !== 66) throw new Error(`${code} has ${books.length} books instead of 66`);
  for (let i = 0; i < 66; i++) {
    if (books[i].id !== i + 1) throw new Error(`${code} book id mismatch: expected ${i+1}, got ${books[i].id}`);
  }

  // Assert verse count (wait, 02-data-architecture said "max(chapter) per book matches canon")
  const chaptersQuery = db.query(`SELECT book_id, max(chapter) as max_chap FROM ${code}_verses GROUP BY book_id`);
  const chapCounts = chaptersQuery.all() as {book_id: number, max_chap: number}[];
  
  for (const row of chapCounts) {
    const canonBook = BOOKS.find(b => b.id === row.book_id);
    if (!canonBook) throw new Error(`Unknown book_id ${row.book_id} in ${code}`);
    if (canonBook.chapters !== row.max_chap) {
      throw new Error(`${code} book ${row.book_id} chapters mismatch: canon=${canonBook.chapters}, db=${row.max_chap}`);
    }
  }

  // Generate chapter stats
  const translationStats: [number, number][][] = [];
  
  for (const book of BOOKS) {
    const bookStats: [number, number][] = [];
    for (let c = 1; c <= book.chapters; c++) {
      const verses = db.query(`SELECT verse, text FROM ${code}_verses WHERE book_id = ? AND chapter = ? ORDER BY verse`).all(book.id, c) as {verse: number, text: string}[];
      
      // Check no gaps in verses
      if (verses.length === 0) throw new Error(`Missing chapter: ${book.id}:${c} in ${code}`);
      for (let i = 0; i < verses.length; i++) {
        if (verses[i].verse !== i + 1) throw new Error(`Verse gap in ${book.id}:${c} in ${code}: expected ${i+1}, got ${verses[i].verse}`);
        if (!verses[i].text || verses[i].text.trim().length === 0) {
          console.warn(`Patching empty text in ${book.id}:${c}:${verses[i].verse} in ${code}`);
          verses[i].text = '[Omitted]';
          db.run(`UPDATE ${code}_verses SET text = ? WHERE book_id = ? AND chapter = ? AND verse = ?`, '[Omitted]', book.id, c, verses[i].verse);
        }
      }

      // Word count: split on whitespace (Lane B convention)
      // "whitespace split numbers — they match what lib/passage-text.ts tokenizes"
      let words = 0;
      for (const v of verses) {
        words += v.text.trim().split(/\s+/).length;
      }
      
      bookStats.push([verses.length, words]);
    }
    translationStats.push(bookStats);
  }

  stats[code] = translationStats;

  // Apply index
  db.run(`CREATE INDEX IF NOT EXISTS ${code}_verses_ref ON ${code}_verses(book_id, chapter, verse)`);

  // Optionally vacuum? Wait, the spec said "Do not VACUUM afterwards: measured, it made the file larger"
  db.close();
}

let out = `/** GENERATED by scripts/prepare-bible-db.ts — do not edit. */\n`;
out += `import type { TranslationCode } from './canon';\n\n`;
out += `export type ChapterStat = readonly [verses: number, words: number];\n`;
out += `export const CHAPTER_STATS: Record<TranslationCode, readonly (readonly ChapterStat[])[]> = {\n`;
for (const code of Object.keys(stats)) {
  out += `  ${code}: ${JSON.stringify(stats[code])},\n`;
}
out += `};\n\n`;
out += `/** Read-aloud pace for scripture, including natural pauses. */\n`;
out += `export const SCRIPTURE_READ_WPM = 140;\n`;
out += `export function estimateMinutes(words: number): number { return words / SCRIPTURE_READ_WPM; }\n`;

fs.writeFileSync(GENERATED_FILE, out);
console.log(`Wrote ${GENERATED_FILE}`);
